[build]
builder = "nixpacks"
buildCommand = "npm install --production=false && npm run build"

[deploy]
startCommand = "npm run db:deploy && npm start"
healthcheckPath = "/api/healthcheck"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
numReplicas = 1

[deploy.websocket]
enabled = true
paths = ["/ws", "/websocket"]
timeout = 300
keepAlive = true
maxConnections = 1000
idleTimeout = 120

[service]
internal_port = 8080
protocol = "http"
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1

[service.http]
force_https = true
keepalive_timeout = 120

[service.ports]
websocket = { handlers = ["http", "websocket"], port = 8080 }