[build]
builder = "nixpacks"
buildCommand = "npm install --production=false && npm run build"

[deploy]
startCommand = "npm run db:deploy && npm start"
healthcheckPath = "/api/healthcheck"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

