[build]
builder = "nixpacks"
buildCommand = "npm install --production=false && npm run build"

[deploy]
startCommand = "npm run db:deploy && npm start"
healthcheckPath = "/api/healthcheck"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
numReplicas = 1

[deploy.websocket]
enabled = true
paths = ["/ws", "/websocket"]
healthcheckPath = "/api/ws-health"
timeout = 300
keepAlive = true
maxConnections = 1000
idleTimeout = 120
handshakeTimeout = 10
closeTimeout = 30
upgradeTimeout = 10

[deploy.websocket.headers]
Connection = ["upgrade"]
Upgrade = ["websocket"]

[service]
internal_port = 8080
protocol = "http"
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1

[service.http]
force_https = true
keepalive_timeout = 120
proxy_request_timeout = 60
proxy_connect_timeout = 10
proxy_send_timeout = 60
proxy_read_timeout = 60

[service.ports]
websocket = { handlers = ["http", "websocket"], port = 8080 }