[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "npx prisma migrate deploy && npm start"
healthcheckPath = "/api/healthcheck"
healthcheckTimeout = 180
healthcheckInterval = 10
restartPolicyType = "on_failure"
numReplicas = 1

[service]
internal_port = 8080
protocol = "http"

[[service.ports]]
port = 8080
handlers = ["http", "websocket"]
force_https = true

[[service.routes]]
path = "/api/*"
handler = "http"

[[service.routes]]
path = "/ws"
handler = "websocket"

[service.websocket]
path = "/ws"
ping_interval = 15000
ping_timeout = 10000
client_tracking = true
proxy_read_timeout = 300
proxy_send_timeout = 300
proxy_connect_timeout = 10
max_connection_age = 600
max_connection_age_grace = 60

[env]
NODE_ENV = "production"
PORT = "8080"
DEBUG = "socket.io:*"

# Required environment variables that need to be set in Railway dashboard:
# DATABASE_URL - PostgreSQL connection string (provided by Railway PostgreSQL plugin)
# UPLOADTHING_SECRET - Your UploadThing secret key
# UPLOADTHING_APP_ID - Your UploadThing app ID
# AUTH_SERVICE_URL - Your authentication service URL
# NEXTAUTH_URL - Your application URL (provided by Railway)
# NEXTAUTH_SECRET - Random string for session encryption