[build]
builder = "nixpacks"
buildCommand = "rm -rf node_modules package-lock.json && npm install && npm run build"

[deploy]
startCommand = "npm run db:deploy && npm start"
healthcheckPath = "/api/healthcheck"
healthcheckTimeout = 180
healthcheckInterval = 10
restartPolicyType = "on_failure"
numReplicas = 1

[service]
internal_port = 8080
protocol = "http"

[[service.ports]]
port = 8080
handlers = ["http", "websocket"]
force_https = true

[service.websocket]
path = "/ws"
ping_interval = 15000
ping_timeout = 10000
client_tracking = true
proxy_read_timeout = 300
proxy_send_timeout = 300
proxy_connect_timeout = 10